name: Integration Tests

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  integration-tests:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.NEGISHI_GITHUB_TOKEN }}
      GITHUB_REPO: ${{ secrets.NEGISHI_GITHUB_REPO }}
      JIRA_API_TOKEN: ${{ secrets.NEGISHI_JIRA_API_TOKEN }}
      JIRA_EMAIL: ${{ secrets.NEGISHI_JIRA_EMAIL }}
      JIRA_BASE_URL: ${{ secrets.NEGISHI_JIRA_BASE_URL }}
      PROJECT_KEY: ${{ secrets.NEGISHI_PROJECT_KEY }}
      # Add any other required env vars here
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run integration tests
        run: |
          python test_integrations.py 